development:
  adapter: mysql2
  database: Mulet_dev
  user: root
  pool: 5
  timeout: 5000
  encoding: utf8
test:
  adapter: mysql2
  database: Mulet_test
  user: root
  pool: 5
  timeout: 5000
  encoding: utf8
production:
  adapter: mysql2
  database: Mulet_prod
  username: root
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000